services:
    hanelyp.jigsawcaptcha.captcha.jigsaw:
        class: hanelyp\jigsawcaptcha\captcha\jigsaw
        calls:
            - [set_name, [hanelyp.jigsawcaptcha.captcha.jigsaw]]
        arguments:
            - @dbal.conn
            - @cache
            - @config
            - @template
            - @user
        tags:
            - { name: captcha.plugins }
